# Generated by Django 3.1.5 on 2021-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=800)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=800)),
                ('url', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Content',
            new_name='HiringContent',
        ),
    ]
